### ISSUE TITLE
[Feature Request] forward proxy support

### ISSUE THREAD

**Issue by visit1985** [stormforger/cli#20]
We would like to use this awesome tool on our internal CI system. But we have a forward proxy between our CI system and the public internet. Could you please make this tool aware of the http(s)_proxy variables.

Thanks!
Keep up the excellent work!

**Comment by tisba** [comment]
Hey @visit1985.

Thanks for your request. It has been added to https://github.com/stormforger/cli/commit/7a416f56f1919f5e403d0812428f2fc1d28ca4ca. `HTTP_PROXY` is now obeyed and accepts `http://` or `socks5://` URLs.

**Comment by tisba** [comment]
I just released [v0.10.0](https://github.com/stormforger/cli/releases/tag/v0.10.0).
