### ISSUE TITLE
Viper config handling kicks in too early | forge not working without .stormforger.toml config file

### ISSUE THREAD

**Issue by MonkeyTonk** [stormforger/cli#56]
using `forge` with version tag 0.30.0 fails with `<timestamp here> Config File ".stormforger" Not Found in "[/Users/<user here>]"`. It fails with every option or command even when using `--help` or `login`which is one of the first commands one has to do.
Having a `.stormforger.toml` (even empty) in the current or user folder is sufficent to get ´forge` back working. 
Some commits ago there came additonal error checks. And I'm quite sure the error check for the `viper.ReadInConfig()` causes this problem. This check also kicks in so early, so that I even cannot use `forge` when having the `STORMFORGER_JWT` env var nor when using the `--jwt` option.

_So current workaround would be:_
Having a `.stormforger.toml` (even empty) in the current or user folder is sufficent to get ´forge` back working.  ;)

**Comment by tisba** [comment]
Hey! Sorry for the glitch :-/ I've fixed the issue in a4e5cf503022c1ee69e17b9cb5ebb16b4a854d6f/[v0.30.1](https://github.com/stormforger/cli/releases/tag/v0.30.1)
