### ISSUE TITLE
Docker - JWT not being saved to stormforger.toml

### ISSUE THREAD

**Issue by hottehead** [stormforger/cli#60]
I run a docker container with 
` docker run stormforger/cli login EMAIL -p PASSWORD`

and it ouputs

>Email: ...
 Login successful!
 Found /root/.stormforger.toml. File will not be overridden!
 Add the JWT token to a .stormforger.toml file like this:

Thus I need to attach the jwt via command line to each call I make. The docker container should be able to store the jwt token by default.

**Environment**
Windows 10
windows containers disabled

**Comment by tisba** [comment]
Hey @hottehead!

Most users are using the Docker version for automation. In those cases they pass in the JWT via the environment.

I'm not sure I follow by what you mean the container should be able to store the JWT by default. Docker uses a copy-on-write system. So changes you make will be discarded when the container stops. You can mount the configuration file into the container if this is what you are looking for.

**Comment by hottehead** [comment]
Hey @tisba,

thanks for the answer. I'll mount the config file to get a persistent storage for the token.
