### ISSUE TITLE
Testcase `validate` regression in version 0.33

### ISSUE THREAD

**Issue by tillkolter** [stormforger/cli#79]
I am currently playing around with the cli and found a discrepancy between version 0.32 and 0.33

In the newest version, my formely valid testcase becomes invalid:

```

1) E23: Evaluation Error
SyntaxError: Invalid or unexpected token
    at test.js:1:0

```

**Comment by tisba** [comment]
Thank you for reporting this. Looks like we missed a spot, @zeisss :(

**Comment by zeisss** [comment]
Hey @tillkolter,

thanks for reporting - do you have a reduced/redacted example for us?

**Comment by tisba** [comment]
I guess this is the problem: https://github.com/stormforger/cli/blob/master/api/testcase.go#L32

**Comment by zeisss** [comment]
Thanks for reporting, I have found the problem and it is located serverside. I will update this issue as soon as we rolled out the fix.

**Comment by zeisss** [comment]
@tillkolter We have deployed a fix. ` forge tc validate zeisss testdata/cases/valid.js` works for me now. Can you verify that this works for you too?

**Comment by zeisss** [comment]
Closing. Please reopen if you still have problems.
